# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import messages_pb2 as messages__pb2


class MessageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CommandMessage = channel.unary_unary(
                '/message.Message/CommandMessage',
                request_serializer=messages__pb2.CommandsRequest.SerializeToString,
                response_deserializer=messages__pb2.CommandsReply.FromString,
                )
        self.UploadFile = channel.unary_unary(
                '/message.Message/UploadFile',
                request_serializer=messages__pb2.FileUploadRequest.SerializeToString,
                response_deserializer=messages__pb2.FileSuccessReply.FromString,
                )


class MessageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CommandMessage(self, request, context):
        """Отправка списка команд для взаимодействия с системой
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFile(self, request, context):
        """Отправка файла на сервер и получение подтверждения о получении
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CommandMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.CommandMessage,
                    request_deserializer=messages__pb2.CommandsRequest.FromString,
                    response_serializer=messages__pb2.CommandsReply.SerializeToString,
            ),
            'UploadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=messages__pb2.FileUploadRequest.FromString,
                    response_serializer=messages__pb2.FileSuccessReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'message.Message', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Message(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CommandMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/message.Message/CommandMessage',
            messages__pb2.CommandsRequest.SerializeToString,
            messages__pb2.CommandsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/message.Message/UploadFile',
            messages__pb2.FileUploadRequest.SerializeToString,
            messages__pb2.FileSuccessReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
